In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [0]:
from skimage.io import imread, imshow
image = imread('11.jpg', as_gray=True)
print (image.shape)
print (image)

(1024, 791)
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [0]:
!pip install opencv-python==3.4.2.16
!pip install opencv-contrib-python==3.4.2.16

     |████████████████████████████████| 25.0MB 1.3MB/s 
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.
  Found existing installation: opencv-python 4.1.2.30
    Uninstalling opencv-python-4.1.2.30:
      Successfully uninstalled opencv-python-4.1.2.30


     |████████████████████████████████| 30.6MB 146kB/s 
  Found existing installation: opencv-contrib-python 4.1.2.30
    Uninstalling opencv-contrib-python-4.1.2.30:
      Successfully uninstalled opencv-contrib-python-4.1.2.30


In [0]:
#SIFT
#!pip install opencv-python==3.4.2.16
#!pip install opencv-contrib-python==3.4.2.16

import cv2
import numpy as np
img=cv2.imread('11.jpg')
gray= cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

sift=cv2.xfeatures2d.SIFT_create()

kp,kd=sift.detectAndCompute(gray,None)

img2= cv2.drawKeypoints(img, kp, outImage = None, color=(255,0,0))
#img=cv2.drawKeypoints(gray,kp)
cv2.imwrite('12.jpg',img2)

print(len(kd[0]))

128


In [0]:
#audio
import os
import matplotlib.pyplot as plt
from scipy.io import wavfile
import numpy as np 
import librosa
import librosa.display
y,sr=librosa.load('1.wav')
S=librosa.feature.melspectrogram(y=y,sr=sr,n_mels=512,n_fft=2048)
fig=plt.figure()
librosa.display.specshow(librosa.power_to_db(S,ref=np.max))
plt.axis('off')
plt.tight_layout()
fig.savefig("im.jpeg",dpi=50,frameon='false')
plt.close()

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:13: MatplotlibDeprecationWarning: 
The frameon kwarg was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use facecolor instead.
  del sys.path[0]


In [0]:
#text
import nltk
import gensim
nltk.download('abc')
from nltk.corpus import abc
nltk.download('punkt')
model=gensim.models.Word2Vec(abc.sents())
x=list(model.wv.vocab)
data=model.wv['science']
print(data)

[nltk_data] Downloading package abc to /root/nltk_data...
[nltk_data]   Package abc is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[ 2.45254263e-01  1.31517828e-01 -2.30070487e-01 -2.07762524e-01
  1.04200520e-01 -1.55027255e-01 -5.10862749e-03 -1.70975462e-01
 -1.16130829e-01 -1.73577949e-01  2.58187763e-02  2.53157467e-01
 -2.24881843e-01 -2.28613764e-02 -4.29070219e-02  2.55227476e-01
 -2.95404911e-01 -4.93593395e-01 -3.39941889e-01 -3.94232005e-01
 -1.54274106e-01  2.00282171e-01  1.66801754e-02 -2.60160059e-01
  3.70493568e-02  3.12185764e-01 -4.49221544e-02 -4.11113769e-01
  4.47207063e-01 -1.24757625e-01  3.09862215e-02  1.28402218e-01
  5.73806107e-01 -2.17865840e-01  5.42759299e-01  3.35121267e-02
  2.08285362e-01  1.80820137e-01 -1.81766063e-01 -2.92717874e-01
  1.72843680e-01  1.47667542e-01 -3.47996593e-01 -3.03195655e-01
 -8.47706664e-03 -2.20846310e-01  2.14781463e-01  7.83798918e-02
  